"""create cves table

Revision ID: 7ae12c6108c5
Revises: 
Create Date: 2026-02-05 00:26:34.742753

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ae12c6108c5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('cves',
#     sa.Column('id', sa.String(), nullable=False),
#     sa.Column('description', sa.Text(), nullable=False),
#     sa.Column('severity', sa.String(), nullable=True),
#     sa.Column('cvss_score', sa.Float(), nullable=True),
#     sa.Column('references', sa.JSON(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_cves_id'), 'cves', ['id'], unique=False)
#     op.create_index(op.f('ix_cves_severity'), 'cves', ['severity'], unique=False)
#     # ### end Alembic commands ###
def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "cves",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(), nullable=True),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("references", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cves_id"), "cves", ["id"], unique=False)
    op.create_index(op.f("ix_cves_severity"), "cves", ["severity"], unique=False)
    op.create_index(
        op.f("ix_cves_cvss_score"), "cves", ["cvss_score"], unique=False
    )  # <--- new line


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cves_cvss_score"), table_name="cves")
    op.drop_index(op.f("ix_cves_severity"), table_name="cves")
    op.drop_index(op.f("ix_cves_id"), table_name="cves")
    op.drop_table("cves")
    # ### end Alembic commands ###
